name: Checkmarx IaC Scan

on:
  push:
  pull_request:

jobs:
  checkmarx-iac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkmarx IaC Scan
        uses: Checkmarx/ast-github-action@main
        with:
          project_name: "IaC-Demo"
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          additional_params: "--sast-scan-types iac --report-format json --fail-on HIGH"
